INFO:2025-09-04 18:06:02,688:MainThread:Dhan.py  started system
INFO:2025-09-04 18:06:02,688:MainThread:STARTED THE PROGRAM
INFO:2025-09-04 19:08:22,545:MainThread:Dhan.py  started system
INFO:2025-09-04 19:08:22,545:MainThread:STARTED THE PROGRAM
INFO:2025-09-04 19:11:40,100:MainThread:Dhan.py  started system
INFO:2025-09-04 19:11:40,102:MainThread:STARTED THE PROGRAM
ERROR:2025-09-04 19:11:44,031:MainThread:Exception in Getting OHLC data as '5'
Traceback (most recent call last):
  File "C:\Users\sakth\miniconda3\envs\dhan\Lib\site-packages\Dhan_Tradehull\Dhan_Tradehull.py", line 520, in get_intraday_data
    df = self.resample_timeframe(df,available_frames[timeframe])
                                    ~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: '5'
INFO:2025-09-04 19:19:16,704:MainThread:Dhan.py  started system
INFO:2025-09-04 19:19:16,705:MainThread:STARTED THE PROGRAM
ERROR:2025-09-04 19:19:20,638:MainThread:Exception in Getting OHLC data as '5m'
Traceback (most recent call last):
  File "C:\Users\sakth\miniconda3\envs\dhan\Lib\site-packages\Dhan_Tradehull\Dhan_Tradehull.py", line 520, in get_intraday_data
    df = self.resample_timeframe(df,available_frames[timeframe])
                                    ~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: '5m'
INFO:2025-09-04 19:33:33,948:MainThread:Dhan.py  started system
INFO:2025-09-04 19:33:33,948:MainThread:STARTED THE PROGRAM
