INFO:2025-09-05 09:39:46,632:MainThread:Dhan.py  started system
INFO:2025-09-05 09:39:46,632:MainThread:STARTED THE PROGRAM
INFO:2025-09-05 12:27:06,295:MainThread:Dhan.py  started system
INFO:2025-09-05 12:27:06,295:MainThread:STARTED THE PROGRAM
INFO:2025-09-05 12:38:13,815:MainThread:Dhan.py  started system
INFO:2025-09-05 12:38:13,816:MainThread:STARTED THE PROGRAM
INFO:2025-09-05 12:47:39,456:MainThread:Dhan.py  started system
INFO:2025-09-05 12:47:39,457:MainThread:STARTED THE PROGRAM
INFO:2025-09-05 12:50:05,733:MainThread:Dhan.py  started system
INFO:2025-09-05 12:50:05,733:MainThread:STARTED THE PROGRAM
ERROR:2025-09-05 12:50:07,075:MainThread:Exception in Getting OHLC data as Check the Tradingsymbol or Exchange
Traceback (most recent call last):
  File "C:\Users\sakth\miniconda3\envs\dhan\Lib\site-packages\Dhan_Tradehull\Dhan_Tradehull.py", line 504, in get_intraday_data
    raise Exception("Check the Tradingsymbol or Exchange")
Exception: Check the Tradingsymbol or Exchange
INFO:2025-09-05 12:51:06,269:MainThread:Dhan.py  started system
INFO:2025-09-05 12:51:06,269:MainThread:STARTED THE PROGRAM
ERROR:2025-09-05 12:51:07,819:MainThread:Exception in Getting OHLC data as Check the Tradingsymbol or Exchange
Traceback (most recent call last):
  File "C:\Users\sakth\miniconda3\envs\dhan\Lib\site-packages\Dhan_Tradehull\Dhan_Tradehull.py", line 504, in get_intraday_data
    raise Exception("Check the Tradingsymbol or Exchange")
Exception: Check the Tradingsymbol or Exchange
INFO:2025-09-05 15:41:22,242:MainThread:Dhan.py  started system
INFO:2025-09-05 15:41:22,243:MainThread:STARTED THE PROGRAM
INFO:2025-09-05 15:57:00,165:MainThread:Dhan.py  started system
INFO:2025-09-05 15:57:00,165:MainThread:STARTED THE PROGRAM
INFO:2025-09-05 16:55:05,976:MainThread:Dhan.py  started system
INFO:2025-09-05 16:55:05,976:MainThread:STARTED THE PROGRAM
ERROR:2025-09-05 16:55:07,619:MainThread:Exception in Getting OHLC data as Check the Tradingsymbol or Exchange
Traceback (most recent call last):
  File "C:\Users\sakth\miniconda3\envs\dhan\Lib\site-packages\Dhan_Tradehull\Dhan_Tradehull.py", line 504, in get_intraday_data
    raise Exception("Check the Tradingsymbol or Exchange")
Exception: Check the Tradingsymbol or Exchange
ERROR:2025-09-05 16:55:09,834:MainThread:Exception in Getting OHLC data as {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
Traceback (most recent call last):
  File "C:\Users\sakth\miniconda3\envs\dhan\Lib\site-packages\Dhan_Tradehull\Dhan_Tradehull.py", line 525, in get_intraday_data
    raise Exception(ohlc)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
ERROR:2025-09-05 16:55:09,874:MainThread:Exception in Getting OHLC data as Check the Tradingsymbol or Exchange
Traceback (most recent call last):
  File "C:\Users\sakth\miniconda3\envs\dhan\Lib\site-packages\Dhan_Tradehull\Dhan_Tradehull.py", line 504, in get_intraday_data
    raise Exception("Check the Tradingsymbol or Exchange")
Exception: Check the Tradingsymbol or Exchange
ERROR:2025-09-05 16:55:09,913:MainThread:Exception in Getting OHLC data as Check the Tradingsymbol or Exchange
Traceback (most recent call last):
  File "C:\Users\sakth\miniconda3\envs\dhan\Lib\site-packages\Dhan_Tradehull\Dhan_Tradehull.py", line 504, in get_intraday_data
    raise Exception("Check the Tradingsymbol or Exchange")
Exception: Check the Tradingsymbol or Exchange
INFO:2025-09-05 16:59:40,256:MainThread:Dhan.py  started system
INFO:2025-09-05 16:59:40,256:MainThread:STARTED THE PROGRAM
ERROR:2025-09-05 16:59:41,739:MainThread:Exception in Getting OHLC data as Check the Tradingsymbol or Exchange
Traceback (most recent call last):
  File "C:\Users\sakth\miniconda3\envs\dhan\Lib\site-packages\Dhan_Tradehull\Dhan_Tradehull.py", line 504, in get_intraday_data
    raise Exception("Check the Tradingsymbol or Exchange")
Exception: Check the Tradingsymbol or Exchange
INFO:2025-09-05 17:07:31,036:MainThread:Dhan.py  started system
INFO:2025-09-05 17:07:31,036:MainThread:STARTED THE PROGRAM
ERROR:2025-09-05 17:07:32,446:MainThread:Exception in Getting OHLC data as Check the Tradingsymbol or Exchange
Traceback (most recent call last):
  File "C:\Users\sakth\miniconda3\envs\dhan\Lib\site-packages\Dhan_Tradehull\Dhan_Tradehull.py", line 504, in get_intraday_data
    raise Exception("Check the Tradingsymbol or Exchange")
Exception: Check the Tradingsymbol or Exchange
INFO:2025-09-05 17:46:59,500:MainThread:Dhan.py  started system
INFO:2025-09-05 17:46:59,500:MainThread:STARTED THE PROGRAM
INFO:2025-09-05 18:11:17,707:MainThread:Dhan.py  started system
INFO:2025-09-05 18:11:17,707:MainThread:STARTED THE PROGRAM
ERROR:2025-09-05 18:11:21,376:MainThread:Exception in Getting OHLC data as {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
Traceback (most recent call last):
  File "c:\Users\sakth\Desktop\VSCODE\TB DHAN API ALGO\Dhan_Tradehull.py", line 525, in get_intraday_data
    raise Exception(ohlc)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
INFO:2025-09-05 18:32:33,117:MainThread:Dhan.py  started system
INFO:2025-09-05 18:32:33,118:MainThread:STARTED THE PROGRAM
ERROR:2025-09-05 18:32:36,848:MainThread:Exception in Getting OHLC data as '5T'
Traceback (most recent call last):
  File "c:\Users\sakth\Desktop\VSCODE\TB DHAN API ALGO\Dhan_Tradehull.py", line 520, in get_intraday_data
    df = self.resample_timeframe(df,available_frames[timeframe])
                                    ~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: '5T'
